## YAML Template.
---
hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
hystrix.command.default.execution.isolation.strategy: THREAD

spring:
  application:
    name: dw-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

      routes:
        - id: userApi
          uri: http://localhost:9902
          predicates:
            - Path=/api/user/**
        - id: CONTACTAPI
          uri: http://localhost:9903
          predicates:
            - Path=/test/**


server:
  port: 9900
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9901/eureka
  instance:
    preferIpAddress: true